#! /bin/sh
#+ Autor:	Ran#
#+ Creado:	19/06/2020 22:17:35
#+ Editado:	10/07/2020 12:11:25

DISTRO=$(lsb_release -a | sed -n '2,+0p' | cut -d: -f2 | tr -ds '\t' '')
RUTA_INI=$(pwd)
CARPETA=/usr/local/bin/

# vamos á carpeta
cd $CARPETA

# baixamos os scripts
echo '> Baixando os scripts: '
$RUTA_INI/gdf ran-n scripts ydl
$RUTA_INI/gdf ran-n scripts metadata
$RUTA_INI/gdf ran-n scripts rmswaps
$RUTA_INI/gdf ran-n scripts 2ogg
$RUTA_INI/gdf ran-n scripts 2pdf
$RUTA_INI/gdf ran-n scripts gc
$RUTA_INI/gdf ran-n scripts gdf
$RUTA_INI/gdf ran-n scripts gl
$RUTA_INI/gdf ran-n scripts pomodoro.py
$RUTA_INI/gdf ran-n scripts aleatorio
$RUTA_INI/gdf ran-n scripts conversor
$RUTA_INI/gdf ran-n scripts copia
$RUTA_INI/gdf ran-n scripts csview
$RUTA_INI/gdf ran-n scripts info
$RUTA_INI/gdf ran-n scripts gfolder
$RUTA_INI/gdf ran-n scripts wifipass
$RUTA_INI/gdf ran-n scripts teras
$RUTA_INI/gdf ran-n scripts crono
$RUTA_INI/gdf ran-n scripts vivo
echo '< BO'

case $DISTRO in
	ManjaroLinux)
		echo ""
		echo "> Baixando os scripts básicos para Arch Linux: "
		$RUTA_INI/gdf ran-n scripts arch/pacma
		$RUTA_INI/gdf ran-n scripts arch/update-grub
		echo '< BO'
		;;
	Arch)
		echo ""
		echo "> Baixando os scripts básicos para Arch Linux: "
		$RUTA_INI/gdf ran-n scripts arch/pacma
		$RUTA_INI/gdf ran-n scripts arch/update-grub
		echo '< BO'
esac

# dámoslle permisos de execución a todo o da carpeta
chmod +x $CARPETA*
