#! /bin/sh
#+ Autor:	Ran#
#+ Creado:	22/04/2020 00:23:18
#+ Editado:	20/06/2020 17:05:52

# Script que copia of ficheiros de configuración da máquina na que estou

printf "> Copiando os ficheiros de configuración...\t"

# configuración de vim
cp -r ~/.config/vim/. media/cnfiles/.config/vim/ #está ahi porque usamos vim -u path para abrir vim

# configuración de neovim
cp -r ~/.config/nvim/. media/cnfiles/.config/nvim/

# bashrc
cp -r ~/.bashrc media/cnfiles/

# bash_aliases
cp -r ~/.bash_aliases media/cnfiles/

#cp -r setup/media/cnfiles/. ~
echo '< BO'
