#! /bin/sh
#+ Autor:	Ran#
#+ Creado:	22/04/2020 00:23:18
#+ Editado:	29/06/2020 23:07:20

# Script que copia of ficheiros de configuración da máquina na que estou

printf "> Copiando os ficheiros de configuración...\t"

# configuración de vim
cp -r ~/.config/vim/. cnfiles/home/.config/vim/ #está ahi porque usamos vim -u path para abrir vim

# configuración de neovim
cp -r ~/.config/nvim/. cnfiles/home/.config/nvim/

# configuración de neovim
cp -r ~/.config/calcurse/. cnfiles/home/.config/calcurse/

# bashrc
cp -r ~/.bashrc cnfiles/home/

# bash_aliases
cp -r ~/.bash_aliases cnfiles/home/

# /etc/profile
cp -r /etc/profile cnfiles/root/etc/

#cp -r setup/media/cnfiles/. ~
echo '< BO'
