#! /bin/sh
#+ Autor:	Ran#
#+ Creado:	07/03/2020 22:33:09
#+ Editado:	30/06/2020 21:26:34

# Script que me permite meter os meus ficheiros de configuración en calquera máquina na que esté a trabalhar

echo "> Pegando os ficheiros de configuración..."

# pedimos o contrasinal para os arquivos privados
#read -ps "> Extraer documentos privados (contrasinal se si, intro se non): " contrasinal
read -p "> Extraer documentos privados (contrasinal se si, intro se non): " contrasinal

# se a poñen extraemos, senón pasamos
[ -z $contrasinal ] && echo '< BO, Sen arquivos privados' || 7z x ./cnfiles/home/.local/share/calcurse_encriptado.7z -o'./cnfiles/home/.local/share/' -aoa -p$contrasinal 2&> /dev/null 
#[ -z $contrasinal ] && echo '< BO, Sen arquivos privados' || 7z x ./cnfiles/home/.local/share/calcurse_encriptado.7z -o'./cnfiles/home/.local/share/' -aoa -p$contrasinal

cp -r cnfiles/home/. ~
rm -f ~/.local/share/calcurse_encriptado.7z
cp -r cnfiles/root/. /

echo "< BO"
