#! /bin/sh
#+ Autor:	Ran#
#+ Creado:	07/03/2020 22:33:09
#+ Editado:	18/07/2020 11:41:18

# Script que me permite meter os meus ficheiros de configuración en calquera máquina na que esté a trabalhar

echo "> Pegando os ficheiros de configuración..."

# pedimos o contrasinal para os arquivos privados
#read -ps "> Extraer documentos privados (contrasinal se si, intro se non): " contrasinal
read -p "> Extraer documentos privados (contrasinal se si, intro se non): " contrasinal

## TODO
## meter todo nun if de docs privados
# calcurse
# se a poñen extraemos, senón pasamos
[ -z $contrasinal ] && echo '< Sen arquivos privados' || &>/dev/null 7z x ./cnfiles/home/.local/share/calcurse_encriptado.7z -o'./cnfiles/home/.local/share/' -aoa -p$contrasinal

# joplin
# se a poñen extraemos, senón pasamos
[ -z $contrasinal ] && echo '< Sen arquivos privados' || &>/dev/null 7z x ./cnfiles/home/.config/joplin_encriptado.7z -o'./cnfiles/home/.config/' -aoa -p$contrasinal

cp -r cnfiles/home/. ~
# calcurse (se non se descomprime non pasa nada que non fai nada)
rm -f ~/.local/share/calcurse_encriptado.7z
rm -rf cnfiles/home/.local/share/calcurse/
# joplin
rm -f ~/.config/joplin_encriptado.7z
rm -rf cnfiles/home/.config/joplin/
ln -sf ~/.config/joplin/  ~/.config/joplin-desktop
sudo cp -r cnfiles/root/. /

echo "< BO"
