#! /bin/sh
#+ Autor:	Ran#
#+ Creado:	22/06/2020 14:42:29
#+ Editado:	30/06/2020 21:54:17

# PROGRAMA PRA MIN PARA PODER TER OS CAMBIOS AOS FICHEIROS AO DÍA MOI FACILMENTE 

# ruta onde está o repositorio
cd ~/Programas/config

# se meto ini fago o link e saio
[ $1 = "ini" ] && sudo ln -sf ~/Programas/config/rconfig_ran /usr/local/bin/rconfig && exit 0


# corremos o programa
./rconfig $1

# se meto copia despois de iniciar o programa fago commit
if [ $1 = "copia" ]; then
    echo "> Facendo a subida dos novos datos."
    {&>/dev/null gc &} && echo "< BO" || echo "< MAL"
fi
