#! /bin/sh
# -*- coding: utf-8 -*-
# ------------------------------------------------------------------------------
#+ Autor:	Ran#
#+ Creado:	08/03/2020 00:13:08
#+ Editado:	2022/11/02 22:50:45.273393
# ------------------------------------------------------------------------------

cd $(dirname $(readlink -f $0))

# se non existe o fich de cnf creao da base
[[ -f .cnf ]] || src/crear-cnf
LINGUA=$(src/uteis/trae-var -v "lang")

operacion_copiado() {
    src/uteis/echo-texto -l $LINGUA -i "titulo.rconfig.operacion_copiado"
    copiar
    src/uteis/echo-texto -l $LINGUA -i "final.rconfig.operacion_copiado"
}

operacion_pegado() {
    src/uteis/echo-texto -l "$LINGUA" -i "titulo.rconfig.operacion_pegado"
    pegar
    src/uteis/echo-texto -l "$LINGUA" -i "final.rconfig.operacion_pegado"
}

operacion_inicio() {
    src/uteis/echo-texto -l "$LINGUA" -i "titulo.rconfig.operacion_inicio"
    inicio
    src/uteis/echo-texto -l "$LINGUA" -i "final.rconfig.operacion_inicio"
}

operacion_axuda() {
    src/uteis/echo-texto -l "$LINGUA" -i "info.axuda.rconfig"
}

copiar() {
    src/copiar-cnfichs
}

pegar() {
    src/pegar-cnfichs
}

inicio() {
    # facer todos os scripts executables
    find src -type f -exec chmod +x -- {} +

    src/crear-carpetas
    echo

    src/baixar-scripts
    echo

    src/instalar-progs
    echo

    # só o inicio porque é algo que se executa
    # a primeira vez, seguindo o ficheiro, e xa
    src/editar-cnfichs
    echo

    pegar
}

while getopts "cpsi" o; do
    case ${o} in
        s|i)
            operacion_inicio
            ;;
        c)
            operacion_copiado
            ;;
        p)
            operacion_pegado
            ;;
        \?)
            operacion_axuda
            ;;
    esac
done

[ "$OPTIND" -eq 1 ] && operacion_axuda
