#! /bin/sh
#+ Autor:	Ran#
#+ Creado:	08/03/2020 00:13:08
#+ Editado:	2022/10/01 12:37:44.804092

cd $(dirname $(readlink -f $0))

# se non existe o fich de cnf creao da base
[[ -f $(pwd)/.cnf ]] || cp $(pwd)/cnf $(pwd)/.cnf
LINGUA=$(grep -w "lang" $(pwd)/.cnf | cut -d= -f2)

mensaxe_axuda(){
    case $LINGUA in
        gz)
            echo 'Hai que indicar se a operación é de copiado(-c), de pegado(-p) ou de inicio(-i).'
            ;;
        en)
            echo 'Indicating the weather the operation is of copy(-c), paste(-p) or setup(-s) is mandatory.'
            ;;
        cas)
            echo 'Hay que indicar si es una operación de copiado(-c), pegado(-p) o inicio(-i).'
            ;;
    esac
}

mensaxe_operacion_inicio(){
    if [[ $1 = "c" ]]; then
        case $LINGUA in
            gz)
                echo '=== Realizando a operación de COPIADO ==='
                echo
                ;;
            en)
                echo '=== Doing the COPY operation ==='
                echo
                ;;
            cas)
                echo '=== Haciendo la operación de COPIADO ==='
                echo
                ;;
        esac
    elif [[ $1 = "p" ]]; then
        case $LINGUA in
            gz)
                echo '=== Realizando a operación de PEGADO ==='
                echo
                ;;
            en)
                echo '=== Doing the PASTE operation ==='
                echo
                ;;
            cas)
                echo '=== Haciendo la operación de PEGADO ==='
                echo
                ;;
        esac
    elif [[ $1 = "s" ]]; then
        case $LINGUA in
            gz)
                echo '=== Realizando a operación de INICIO ==='
                echo
                ;;
            en)
                echo '=== Doing the SETUP operation ==='
                echo
                ;;
            cas)
                echo '=== Haciendo la operación de INICIO ==='
                echo
                ;;
        esac
    fi
}

mensaxe_operacion_fin(){
    if [[ $1 = "c" ]]; then
        case $LINGUA in
            gz)
                echo
                echo '=== Fin da operación de COPIADO ==='
                ;;
            en)
                echo
                echo '=== End of the COPY operation ==='
                ;;
            cas)
                echo
                echo '=== Fin de la operación de COPIADO ==='
                ;;
        esac
    elif [[ $1 = "p" ]]; then
        case $LINGUA in
            gz)
                echo
                echo '=== Fin da operación de PEGADO ==='
                ;;
            en)
                echo
                echo '=== End of the PASTE operation ==='
                ;;
            cas)
                echo
                echo '=== Fin de la operación de PEGADO ==='
                ;;
        esac
    elif [[ $1 = "s" ]]; then
        case $LINGUA in
            gz)
                echo
                echo '=== Fin da operación de INICIO ==='
                ;;
            en)
                echo
                echo '=== End of the SETUP operation ==='
                ;;
            cas)
                echo
                echo '=== Fin de la operación de INICIO ==='
                ;;
        esac
    fi
}

mensaxe_operacion(){
    case $1 in
        inicio)
            mensaxe_operacion_inicio $2
            ;;
        fin)
            mensaxe_operacion_fin $2
            ;;
    esac
}

copiar(){
    $(pwd)/src/copiar-cnfichs
}

pegar() {
    $(pwd)/src/pegar-cnfichs
}

inicio() {
    $(pwd)/src/crear-carpetas
    echo
    $(pwd)/src/baixar-scripts
    echo
    $(pwd)/src/instalar-progs
    echo
    pegar
}

# se non meten variable pois pon mensaxe e sae
if [ -z $1 ]; then
    mensaxe_axuda
    exit 1
fi

case $1 in
    -c|--copiar|--copy)
        mensaxe_operacion "inicio" "c"
        copiar
        mensaxe_operacion "fin" "c"
        ;;

    -p|--pegar|--paste)
        mensaxe_operacion "inicio" "p"
        pegar
        mensaxe_operacion "fin" "p"
        ;;

    -s|--setup|-i|--inicio)
        mensaxe_operacion "inicio" "s"
        inicio
        mensaxe_operacion "fin" "s"
        ;;

    *)
        mensaxe_axuda
        ;;
esac
