#! /bin/sh
#+ Autor:	Ran#
#+ Creado:	22/06/2020 01:44:31
#+ Editado:	22/06/2020 01:54:24

# USO PERSOAL PARA CANDO MODIFIQUE OS FICHEIROS NON TER QUE IR Á CARPETA PARA EXECUTAR O COMANDO
# uso:
# cp runconfig /usr/local/bin/rconfig
# a usar rconfig tendoo no path
# isto só interesante pra min porque son o único que pode subir ao repo
# o uso normal será simplemente baixalo, executar o pegar e borrar o git

cd /home/ran/Programas/config
./rconfig $1
