#! /bin/sh
# -*- coding: utf-8 -*-
# ------------------------------------------------------------------------------
#+ Autor:  	Ran#
#+ Creado: 	2022/10/06 20:14:30.260275
#+ Editado:	2022/10/07 02:38:49.311816
# ------------------------------------------------------------------------------

#* Script para sacar o texto correcto no idioma correcto.
#* Script to prompt text in the correct language.

FICH=$(pwd)"/media/i18n.csv"

SEP=$(grep -w "^csv_separator" $(pwd)/.cnf | cut -d= -f2)
SEP_CATEX=$(grep -w "^csv_string" $(pwd)/.cnf | cut -d= -f2)

while getopts "l:i:" o; do
    case "${o}" in
        l)
            lang=$OPTARG
            ;;
        i)
            id=$OPTARG
            ;;
    esac
done

[[ -n $lang && -n id ]]\
    && texto=$(grep ^$id$SEP$lang $FICH | cut -d$SEP_CATEX -f2)

[[ -n $texto ]]\
    && echo $texto
