#! /bin/sh
# -*- coding: utf-8 -*-
# ------------------------------------------------------------------------------
#+ Autor:  	Ran#
#+ Creado: 	2022/10/10 14:12:56.082178
#+ Editado:	2022/10/10 14:24:52.289940
# ------------------------------------------------------------------------------

#* Usual info needed for the scripts put up all in the same file for convenience.

while getopts "udhf" o; do
    case "${o}" in
        # distro name
        d)
            echo $(lsb_release -a | sed -n '2,+0p' | cut -d: -f2 | tr -ds '\t' '')
            ;;

        # user name
        u)
            echo ${SUDO_USER:-${USER}}
            ;;

        # home folder
        h|f)
            echo $(eval echo "~${SUDO_USER:-${USER}}")
            ;;
    esac
done
