#! /bin/sh
# -*- coding: utf-8 -*-
# ------------------------------------------------------------------------------
#+ Autor:  	Ran#
#+ Creado: 	2022/10/10 14:12:56.082178
#+ Editado:	2024/05/05 13:30:52.289940
# ------------------------------------------------------------------------------

#* Usual info needed for the scripts put up all in the same file for convenience.

while getopts "udhf" o; do
    case "${o}" in
        # distro name
        d)
            echo $(lsb_release -i | cut -d$'\t' -f2)
            ;;

        # user name
        u)
            echo ${SUDO_USER:-${USER}}
            ;;

        # home folder
        h|f)
            echo $(eval echo "~${SUDO_USER:-${USER}}")
            ;;
    esac
done
