#! /bin/sh
# -*- coding: utf-8 -*-
# ------------------------------------------------------------------------------
#+ Autor:  	Ran#
#+ Creado: 	2022/10/07 14:10:28.447383
#+ Editado:	2022/10/28 20:22:59.208929
# ------------------------------------------------------------------------------

#* Script para ler o ficheiro de configuración e devolver o valor da variable pedida.
#* Script that reads the config file and returns the requested variable.

while getopts "v:" o; do
    case "${o}" in
        v)
            echo $(grep -w "^$OPTARG=.*" .cnf | cut -d= -f2-)
            ;;
    esac
done
