#! /bin/sh
# -*- coding: utf-8 -*-
# ------------------------------------------------------------------------------
#+ Autor:  	Ran#
#+ Creado: 	2022/10/07 14:10:28.447383
#+ Editado:	2022/10/28 20:38:48.038120
# ------------------------------------------------------------------------------

#* Script para ler o ficheiro de configuración e devolver o valor da variable pedida.
#* Script that reads the config file and returns the requested variable.

while getopts "v:f:" o; do
    case "${o}" in
        v)
            var=$OPTARG
            ;;
        f)
            file=$OPTARG
            ;;
    esac
done

[[ -z $file ]] && file=".cnf"
# desta forma non fai un echo baleiro cando non mete a opción -v
[[ -n $var ]] && echo $(grep -w "^""$var""=.*" "$file" | cut -d= -f2-)
