#! /bin/sh
#+ Autor:	Ran#
#+ Creado:	08/03/2020 00:07:50
#+ Editado:	28/04/2020 16:18:32

#* Script para copiar os scripts básicos directamente a /usr/local/bin

DISTRO=$(lsb_release -a | sed -n '2,+0p' | cut -d: -f2 | tr -ds '\t' '')

printf "Pegando os scripts básicos a /usr/local/bin...\t"
cp ydl metadata rmswaps 2ogg 2pdf gc gdf gl pomodoro.py aleatorio conversor copia csview info gfolder wifipass teras crono /usr/local/bin

printf "OK\n"

case $DISTRO in
	ManjaroLinux)
		printf "Pegando scripts básicos para Arch Linux...\t"
		cp arch/pacma arch/update-grub /usr/local/bin
		printf "OK\n"
		;;
esac

