#! /bin/sh
#+ Autor:	Ran#
#+ Creado:	19/06/2020 22:17:35
#+ Editado:	2022/08/31 22:00:15.392179

# mirar se o script se executa como root
# de non, facer que así sexa
if [[ $(/usr/bin/id -u) != 0 ]]; then
    if whereis sudo &>/dev/null; then
        # correr o script de novo como sudo e cos parametros dados
        sudo $0 $*
        # para que non se execute dúas veces
        exit 0
    else
        # saída con erro
        exit 1
    fi
fi

CARPETA_DESTINO="/usr/local/scripts/"

FICH=$(pwd)"/media/scripts.csv"
DISTRO=$(lsb_release -a | sed -n '2,+0p' | cut -d: -f2 | tr -ds '\t' '')
LINGUA=$(grep -w "lang" $(pwd)/.config | cut -d= -f2)
VERBOSE=$(grep -w "verbose" $(pwd)/.config | cut -d= -f2)

# mensaxe de inicio
case $LINGUA in
    gz)
        echo '► Baixando os scripts:'
        ;;
    en)
        echo '► Downloading the scripts:'
        ;;
    cas)
        echo '► Bajando los scripts:'
        ;;
esac

# crear (se non existe) a carpeta e ponherse nela
mkdir -p $CARPETA_DESTINO
cd $CARPETA_DESTINO


# loop polas filas do script
while read line; do
    if [[ $line = ,* || $line = $DISTRO* ]]; then
        USUARIO=$(echo "$line" | cut -d, -f2)
        REPOSITORIO=$(echo "$line" | cut -d, -f3)
        NOME=$(echo "$line" | cut -d, -f4)
        NOVO_NOME=$(echo "$line" | cut -d, -f5)

        # estes dous comandos precisan de sudo, correrase o script como sudo
        # mirar que o novo nome teña contido
        if [ -n "$NOVO_NOME" ]; then
            # a primeira parte do if por se non pon nada
            if [ $VERBOSE ] && [ $VERBOSE -eq 1 ]; then
                wget -N https://raw.githubusercontent.com/"$USUARIO"/"$REPOSITORIO"/master/"$NOME" -q --show-progress -O "$NOVO_NOME"
            else
                wget -N https://raw.githubusercontent.com/"$USUARIO"/"$REPOSITORIO"/master/"$NOME" -q -O "$NOVO_NOME"
            fi
            chmod +x "$NOVO_NOME"
        # se o novo nome está baleiro usase o nome que xa ten
        else
            if [ $VERBOSE ] && [ $VERBOSE -eq 1 ]; then
                wget -N https://raw.githubusercontent.com/"$USUARIO"/"$REPOSITORIO"/master/"$NOME" -q --show-progress
            else
                wget -N https://raw.githubusercontent.com/"$USUARIO"/"$REPOSITORIO"/master/"$NOME" -q
            fi
            chmod +x $(echo $NOME | rev | cut -d/ -f1 | rev)
        fi
    fi
done < $FICH


# mensaxe de fin
case $LINGUA in
    gz)
        echo '◄ BO'
        ;;
    en)
        echo '◄ OK'
        ;;
    cas)
        echo '◄ OK'
        ;;
esac
