#! /bin/sh
#+ Autor:	Ran#
#+ Creado:	19/06/2020 22:17:35
#+ Editado:	2022/10/07 14:24:32.632203

# mirar se o script se executa como root
# de non, facer que así sexa
if [[ $(/usr/bin/id -u) != 0 ]]; then
    if whereis sudo &>/dev/null; then
        # correr o script de novo como sudo e cos parametros dados
        sudo $0 $*
        # para que non se execute dúas veces
        exit 0
    else
        # saída con erro
        exit 1
    fi
fi

FICH=$(pwd)"/media/scripts.csv"

DISTRO=$(lsb_release -a | sed -n '2,+0p' | cut -d: -f2 | tr -ds '\t' '')

LINGUA=$($(pwd)/src/uteis/trae-var -v "lang")
VERBOSE=$($(pwd)/src/uteis/trae-var -v "verbose")
CARPETA_DESTINO=$($(pwd)/src/uteis/trae-var -v "scripts_folder")


$(pwd)/src/uteis/echo-texto -l $LINGUA -i "titulo.baixar_scripts"

# crear (se non existe) a carpeta
mkdir -p $CARPETA_DESTINO

# link ó ficheiro principal
[[ $VERBOSE -eq 1 ]]\
    && ln -sfv $(pwd)"/rconfig" $CARPETA_DESTINO\
    || ln -sf $(pwd)"/rconfig" $CARPETA_DESTINO

# ir á carpeta onde se van descargar os scripts
cd $CARPETA_DESTINO

# loop polas filas do script
while read line; do
    # so os que comecen por coma ou pola distro correcta
    if [[ $line = ,* || $line = $DISTRO* ]]; then
        USUARIO=$(echo "$line" | cut -d, -f2)
        REPOSITORIO=$(echo "$line" | cut -d, -f3)
        NOME=$(echo "$line" | cut -d, -f4)
        NOVO_NOME=$(echo "$line" | cut -d, -f5)

        # estes dous comandos precisan de sudo, correrase o script como sudo
        # mirar que o novo nome teña contido
        if [ -n "$NOVO_NOME" ]; then
            # a primeira parte do if por se non pon nada
            [[ $VERBOSE -eq 1 ]]\
                && wget -N https://raw.githubusercontent.com/"$USUARIO"/"$REPOSITORIO"/master/"$NOME" -q --show-progress -O "$NOVO_NOME"\
                || wget -N https://raw.githubusercontent.com/"$USUARIO"/"$REPOSITORIO"/master/"$NOME" -q -O "$NOVO_NOME"
            chmod +x "$NOVO_NOME"
        # se o novo nome está baleiro usase o nome que xa ten
        else
            [[ $VERBOSE -eq 1 ]]\
                && wget -N https://raw.githubusercontent.com/"$USUARIO"/"$REPOSITORIO"/master/"$NOME" -q --show-progress\
                || wget -N https://raw.githubusercontent.com/"$USUARIO"/"$REPOSITORIO"/master/"$NOME" -q
            chmod +x $(echo $NOME | rev | cut -d/ -f1 | rev)
        fi
    fi
done < $FICH

$(pwd)/src/uteis/echo-texto -l $LINGUA -i "final.ok"
