#! /bin/sh
#+ Autor:	Ran#
#+ Creado:	22/04/2020 00:23:18
#+ Editado:	2022/10/07 14:06:01.221680

#* Script que copia of ficheiros de configuración da máquina na que estou

copiar_elemento () {
    # carpetas
    if [[ $2 == */ ]]; then
        if [[ ! -d $1 ]]; then
            [[ $VERBOSE -eq 1 ]] && mkdir -vp $1 || mkdir -p $1
        fi
        [[ $VERBOSE -eq 1 ]] && cp -vupfr $2. $1 || cp -upfr $2. $1
    # ficheiros
    else
        if [[ ! -d $(dirname $1) ]]; then
            [[ $VERBOSE -eq 1 ]] && mkdir -vp $(dirname $1) || mkdir -p $(dirname $1)
        fi
        [[ $VERBOSE -eq 1 ]] && cp -vupfr $2 $1 || cp -upfr $2 $1
    fi
}

eliminar () {
    array=($(echo $2 | tr $SEP2 "\n"))
    for fich in "${array[@]}"; do
        [[ $VERBOSE -eq 1 ]]\
            && find "$1" -name "$fich" -exec rm -vrf {} +\
            || find "$1" -name "$fich" -exec rm -rf {} +
    done
}

# mirar se o script se executa como root
# de non, facer que así sexa
if [[ $(/usr/bin/id -u) != 0 ]]; then
    if whereis sudo &>/dev/null; then
        # correr o script de novo como sudo e cos parametros dados
        sudo $0 $*
        # para que non se execute dúas veces
        exit 0
    else
        # saída con erro
        exit 1
    fi
fi

FICH=$(pwd)"/media/arquivos.csv"

USER=${SUDO_USER:-${USER}}

LINGUA=$(grep -w "^lang" $(pwd)/.cnf | cut -d= -f2)
VERBOSE=$(grep -w "^verbose" $(pwd)/.cnf | cut -d= -f2)
ACCEPT_ENCRIPT=$(grep -w "^accept_encryption" $(pwd)/.cnf | cut -d= -f2)
CONTRASINAL=$(grep -w "^passwd" $(pwd)/.cnf | cut -d= -f2)
SEP=$(grep -w "^csv_separator" $(pwd)/.cnf | cut -d= -f2)
SEP2=$(grep -w "^csv_separator2" $(pwd)/.cnf | cut -d= -f2)
CNFOLDER=$(grep -w "^cnfolder" $(pwd)/.cnf | cut -d= -f2)
CNFOLDER_HOME=$(grep -w "^cnfolder_home" $(pwd)/.cnf | cut -d= -f2)
CNFOLDER_ROOT=$(grep -w "^cnfolder_root" $(pwd)/.cnf | cut -d= -f2)

FOGAR=$(eval echo "~$USER")


$(pwd)/src/uteis/echo-texto -l $LINGUA -i "titulo.copiar_cnfichs"

while read line; do
    # ignorar liñas comentadas ou baleiras
    if [[ $line != \#* && -n $line ]]; then
        encriptar=$(echo $line | cut -d$SEP -f1)
        ruta=$(echo $line | cut -d$SEP -f2)
        excluir=$(echo $line | cut -d$SEP -f3)

        if [[ $ruta = \~* ]]; then
            ruta=$(echo $ruta | cut -d~ -f2)
            ruta_total=$(echo $(pwd)/$CNFOLDER/$CNFOLDER_HOME$(dirname $ruta)/$(basename $ruta) | sed 's/\/\//\//g')
            ruta=$FOGAR$ruta
        else
            ruta_total=$(pwd)/$CNFOLDER/$CNFOLDER_ROOT$(dirname $ruta)/$(basename $ruta)
        fi

        copiar_elemento $ruta_total $ruta

        [[ -n $excluir ]] && eliminar $ruta_total $excluir

        if [[ -n $CONTRASINAL && $encriptar -eq $ACCEPT_ENCRIPT ]]; then
            if [[ $VERBOSE -eq 1 ]]; then
                7z a $ruta_total $ruta_total -p$CONTRASINAL -mhe=on -mx=9 -bb1
                rm -vrf $ruta_total
            else
                7z a $ruta_total $ruta_total -p$CONTRASINAL -mhe=on -mx=9 2&>/dev/null
                rm -rf $ruta_total
            fi
        fi
    fi
done < $FICH

# preciso cambiar isto porque se executa como root e quedaría como owner
chown -R $USER:$USER $(pwd)/$CNFOLDER

$(pwd)/src/uteis/echo-texto -l $LINGUA -i "final.ok"
