#! /bin/sh
# -*- coding: utf-8 -*-
# ------------------------------------------------------------------------------
#+ Autor:	Ran#
#+ Creado:	22/04/2020 00:23:18
#+ Editado:	2022/10/30 21:51:51.338116
# ------------------------------------------------------------------------------

#*gz* Script que copia of ficheiros da máquina na que se executa.
#*en* Script to copy the selected files of the machine it is run at.

copiar_elemento () {
    # carpetas
    if [[ "$2" == */ ]]; then
        if [[ ! -d "$1" ]]; then
            [[ "$VERBOSE" -eq 1 ]] && mkdir -vp "$1" || mkdir -p "$1"
        fi
        [[ "$VERBOSE" -eq 1 ]] && cp -vpfr "$2". "$1" || cp -pfr "$2". "$1"
    # ficheiros
    else
        if [[ ! -d $(dirname "$1") ]]; then
            [[ "$VERBOSE" -eq 1 ]] && mkdir -vp $(dirname "$1") || mkdir -p $(dirname "$1")
        fi
        [[ "$VERBOSE" -eq 1 ]] && cp -vpfr "$2" "$1" || cp -pfr "$2" "$1"
    fi
}

eliminar () {
    array=($(echo "$2" | tr "$SEP2" "\n"))
    for fich in "${array[@]}"; do
        [[ "$VERBOSE" -eq 1 ]]\
            && find "$1" -name "$fich" -exec rm -vrf {} +\
            || find "$1" -name "$fich" -exec rm -rf {} +
    done
}

# mirar se o script se executa como root
# de non, facer que así sexa
if [[ $(/usr/bin/id -u) != 0 ]]; then
    if whereis sudo &>/dev/null; then
        # correr o script de novo como sudo e cos parametros dados
        sudo $0 $*
        # para que non se execute dúas veces
        exit 0
    else
        # saída con erro
        exit 1
    fi
fi

FICH="media/arquivos.csv"

USER=$(src/uteis/trae-elto -u)
FOGAR=$(src/uteis/trae-elto -h)
DISTRO=$(src/uteis/trae-elto -d)

LINGUA=$(src/uteis/trae-var -v "lang")
VERBOSE=$(src/uteis/trae-var -v "verbose")
ACCEPT_ENCRIPT=$(src/uteis/trae-var -v "accept_encryption")
CONTRASINAL=$(src/uteis/trae-var -v "passwd")
SEP=$(src/uteis/trae-var -v "csv_separator")
SEP2=$(src/uteis/trae-var -v "csv_separator2")
CNFOLDER=$(src/uteis/trae-var -v "cnfolder")
CNFOLDER_HOME=$(src/uteis/trae-var -v "cnfolder_home")
CNFOLDER_ROOT=$(src/uteis/trae-var -v "cnfolder_root")


src/uteis/echo-texto -l "$LINGUA" -i "titulo.copiar_cnfichs"

while read line; do
    # ignorar linhas comentadas ou baleiras
    if [[ "$line" != \#* && -n "$line" ]]; then
        encriptar=$(echo "$line" | cut -d$SEP -f1)
        ruta=$(echo "$line" | cut -d$SEP -f2)
        excluir=$(echo "$line" | cut -d$SEP -f3)
        distros=$(echo "$line" | cut -d$SEP -f4)

        if [[ -z "$distros" ]] || (echo "$distros" | grep -w "$DISTRO" > /dev/null); then
            if [[ "$ruta" = \~* ]]; then
                ruta=$(echo "$ruta" | cut -d~ -f2-)
                ruta_total=$(echo "$CNFOLDER"/"$CNFOLDER_HOME"$(dirname "$ruta")/$(basename "$ruta") | sed 's/\/\//\//g')
                ruta="$FOGAR$ruta"
            else
                ruta_total="$CNFOLDER"/"$CNFOLDER_ROOT"$(dirname "$ruta")/$(basename "$ruta")
            fi

            copiar_elemento "$ruta_total" "$ruta"

            [[ -n "$excluir" ]] && eliminar "$ruta_total" "$excluir"

            if [[ "$encriptar" -eq "$ACCEPT_ENCRIPT" ]]; then
                if [[ "$VERBOSE" -eq 1 ]]; then
                    echo
                    [[ -n "$CONTRASINAL" ]]\
                        && 7z a "$ruta_total" "$ruta_total" -p"$CONTRASINAL" -mhe=on -mx=9 -bb1\
                        || {
                                [[ -f "$ruta_total".7z ]] && rm "$ruta_total".7z
                                7z a "$ruta_total" "$ruta_total" -mhe=on -mx=9 -bb1
                            }
                    echo
                    rm -vrf "$ruta_total"
                else
                    [[ -n "$CONTRASINAL" ]]\
                        && 7z a "$ruta_total" "$ruta_total" -p"$CONTRASINAL" -mhe=on -mx=9 2&>/dev/null\
                        || {
                                [[ -f "$ruta_total".7z ]] && rm "$ruta_total".7z
                                7z a "$ruta_total" "$ruta_total" -mhe=on -mx=9 2&>/dev/null
                            }

                    rm -rf "$ruta_total"
                fi
            fi
        fi
    fi
done < "$FICH"

# preciso cambiar isto porque se executa como root e quedaría como owner
chown -R "$USER":"$USER" "$CNFOLDER"

src/uteis/echo-texto -l "$LINGUA" -i "final.ok"
