#! /bin/sh
# -*- coding: utf-8 -*-
# ------------------------------------------------------------------------------
#+ Autor:  	Ran#
#+ Creado: 	2022/10/05 21:58:48.495625
#+ Editado:	2022/10/05 22:21:49.458419
# ------------------------------------------------------------------------------

mensaxe_contrasinal(){
    case $LINGUA in
        gz)
            echo 'Indica o contrasinal (baleiro para ningún)'
            ;;
        en)
            echo 'Enter password (empty for none)'
            ;;
        cas)
            echo 'Indica la contraseña (vacío para ninguna)'
            ;;
    esac
}

# copiase o ficheiro
cp $(pwd)/cnf $(pwd)/.cnf

echo
echo "Galego (gz)"
echo "English (en)"
echo "Castellano (cas)"
read -p "LANG: " lang
echo

sed -i 's/lang=.*/lang='"$lang"'/g' $(pwd)/.cnf

LINGUA=$(grep -w "lang" $(pwd)/.cnf | cut -d= -f2)

mensaxe_contrasinal

read -s contrasinal

sed -i 's/passwd=.*/passwd='"$contrasinal"'/g' $(pwd)/.cnf

echo
