#! /bin/sh
# -*- coding: utf-8 -*-
# ------------------------------------------------------------------------------
#+ Autor:  	Ran#
#+ Creado: 	2022/10/05 21:58:48.495625
#+ Editado:	2022/10/24 18:36:10.022773
# ------------------------------------------------------------------------------

# copiase o ficheiro
cp cnf .cnf

echo
echo "Galego (gz)"
echo "English (en)"
echo "Castellano (cas)"
read -p "LANG: " lang
echo

sed -i 's/lang=.*/lang='"$lang"'/g' .cnf

LINGUA=$(src/uteis/trae-var -v "lang")

src/uteis/echo-texto -l $LINGUA -i "mensaxe.usuario.indicar_contrasinal"

read -s contrasinal

sed -i 's/passwd=.*/passwd='"$contrasinal"'/g' .cnf

echo
