#! /bin/sh
#+ Autor:	Ran#
#+ Creado:	08/03/2020 13:31:26
#+ Editado:	2022/09/05 22:17:19.601534

# mirar se o script se executa como root
# de non, facer que así sexa
if [[ $(/usr/bin/id -u) != 0 ]]; then
    if whereis sudo &>/dev/null; then
        # correr o script de novo como sudo e cos parametros dados
        sudo $0 $*
        # para que non se execute dúas veces
        exit 0
    else
        # saída con erro
        exit 1
    fi
fi

LINGUA=$(grep -w "lang" $(pwd)/.cnf | cut -d= -f2)
VERBOSE=$(grep -w "verbose" $(pwd)/.cnf | cut -d= -f2)
FICH=$(pwd)"/media/carpetas.csv"
FOGAR=$(eval echo "~$(who -m | awk '{ print $1 }')")


case $LINGUA in
    gz)
        echo "► Creando ou modificando os nomes das carpetas"
        ;;
    en)
        echo "► Creating our modifying the names of the folders"
        ;;
    cas)
        echo "► Creando o modificando los nombres de las carpetas"
        ;;
esac


# rename dos nomes usuais por defecto
mv $FOGAR/Desktop $FOGAR/Escritorio 2> /dev/null
mv $FOGAR/Documents $FOGAR/Documentos 2> /dev/null
mv $FOGAR/Downloads $FOGAR/Descargas 2> /dev/null
mv $FOGAR/Music $FOGAR/Música 2> /dev/null
mv $FOGAR/Pictures $FOGAR/Imaxes 2> /dev/null
#mv $FOGAR/Public $FOGAR/Público 2> /dev/null
#mkdir -p $FOGAR/Público
rm -rf $FOGAR/Public
mv $FOGAR/Software $FOGAR/Programas 2> /dev/null
mv $FOGAR/Videos $FOGAR/Vídeos 2> /dev/null


while read line; do
    if [[ $line != \#* && -n $line ]]; then
        if [[ $line = \~* ]]; then
            carpeta=$FOGAR$(echo $line | cut -d~ -f2)
        else
            carpeta=$line
        fi

        if [ $VERBOSE ] && [ $VERBOSE -eq 1 ]; then
            echo $line
        fi
        mkdir -p $carpeta
    fi
done < $FICH

case $LINGUA in
    gz)
        echo "◄ BO"
        ;;
    en)
        echo "◄ OK"
        ;;
    cas)
        echo "◄ OK"
        ;;
esac
