#! /bin/sh
#+ Autor:	Ran#
#+ Creado:	08/03/2020 13:31:26
#+ Editado:	2022/08/31 22:00:42.419085

# mirar se o script se executa como root
# de non, facer que así sexa
if [[ $(/usr/bin/id -u) != 0 ]]; then
    if whereis sudo &>/dev/null; then
        # correr o script de novo como sudo e cos parametros dados
        sudo $0 $*
        # para que non se execute dúas veces
        exit 0
    else
        # saída con erro
        exit 1
    fi
fi

LINGUA=$(grep -w "lang" $(pwd)/.config | cut -d= -f2)
VERBOSE=$(grep -w "verbose" $(pwd)/.config | cut -d= -f2)
FICH=$(pwd)"/media/carpetas.csv"

case $LINGUA in
    gz)
        echo "► Creando ou modificando os nomes das carpetas"
        ;;
    en)
        echo "► Creating our modifying the names of the folders"
        ;;
    cas)
        echo "► Creando o modificando los nombres de las carpetas"
        ;;
esac


# rename dos nomes usuais por defecto
mv ~/Desktop ~/Escritorio 2> /dev/null
mv ~/Documents ~/Documentos 2> /dev/null
mv ~/Downloads ~/Descargas 2> /dev/null
mv ~/Music ~/Música 2> /dev/null
mv ~/Pictures ~/Imaxes 2> /dev/null
#mv ~/Public ~/Público 2> /dev/null
#mkdir -p ~/Público
rm -rf ~/Public
mv ~/Software ~/Programas 2> /dev/null
mv ~/Videos ~/Vídeos 2> /dev/null


while read line; do
    if [ $VERBOSE ] && [ $VERBOSE -eq 1 ]; then
        echo $line
    fi
    mkdir -p $line
done < $FICH

case $LINGUA in
    gz)
        echo "◄ BO"
        ;;
    en)
        echo "◄ OK"
        ;;
    cas)
        echo "◄ OK"
        ;;
esac
