#! /bin/sh
# -*- coding: utf-8 -*-
# ------------------------------------------------------------------------------
#+ Autor:  	Ran#
#+ Creado: 	2022/10/05 21:58:48.495625
#+ Editado:	2022/10/05 22:21:49.458419
# ------------------------------------------------------------------------------

# copiase o ficheiro
cp $(pwd)/cnf $(pwd)/.cnf

echo
echo "Galego (gz)"
echo "English (en)"
echo "Castellano (cas)"
read -p "LANG: " lang
echo

sed -i 's/lang=.*/lang='"$lang"'/g' $(pwd)/.cnf

LINGUA=$(grep -w "lang" $(pwd)/.cnf | cut -d= -f2)

$(pwd)/src/echo-texto -l $LINGUA -i "mensaxe.usuario.indicar_contrasinal"

read -s contrasinal

sed -i 's/passwd=.*/passwd='"$contrasinal"'/g' $(pwd)/.cnf

echo
