#! /bin/sh
# -*- coding: utf-8 -*-
# ------------------------------------------------------------------------------
#+ Autor:  	Ran#
#+ Creado: 	2022/09/09 16:41:29.164675
#+ Editado:	2022/10/07 14:07:03.950057
# ------------------------------------------------------------------------------

# mirar se o script se executa como root
# de non, facer que así sexa
if [[ $(/usr/bin/id -u) != 0 ]]; then
    if whereis sudo &>/dev/null; then
        # correr o script de novo como sudo e cos parametros dados
        sudo $0 $*
        # para que non se execute dúas veces
        exit 0
    else
        # saída con erro
        exit 1
    fi
fi

FICH=$(pwd)"/media/progs.csv"
FICH2=$(pwd)"/media/progs_descs.csv"

USER=${SUDO_USER:-${USER}}

LINGUA=$(grep -w "^lang" $(pwd)/.cnf | cut -d= -f2)
VERBOSE=$(grep -w "^verbose" $(pwd)/.cnf | cut -d= -f2)
SEP=$(grep -w "^csv_separator" $(pwd)/.cnf | cut -d= -f2)
SEP2=$(grep -w "^csv_separator2" $(pwd)/.cnf | cut -d= -f2)
SEP_CATEX=$(grep -w "^csv_string" $(pwd)/.cnf | cut -d= -f2)
AUR_PKG_MANAGER=$(grep -w "^aur_pkg_manager" $(pwd)/.cnf | cut -d= -f2)
DISTRO=$(lsb_release -a | sed -n '2,+0p' | cut -d: -f2 | tr -ds '\t' '')
NUM_PROGS=$(grep "^[^#]" $FICH | grep -E ",,|$DISTRO" | wc -l)

TEMP_SPACE=":-:"

pkg_install(){
    case $repositorio in
        "")
            case $DISTRO in
                "ArcoLinux"\
                |"Manjaro")
                    pacman -S $id_nome --noconfirm --needed > /dev/null 2>&1
                    #pacman -S $id_nome --noconfirm --needed
                    ;;
            esac
            ;;
        aur)
            sudo -u $USER $AUR_PKG_MANAGER -S $id_nome --noconfirm --needed > /dev/null 2>&1
            #sudo -u $USER $AUR_PKG_MANAGER -S $id_nome --noconfirm --needed
            ;;
        git)
            echo GIT
            ;;
    esac
}

install_pkg(){
    #local id_nome=$1
    #local repositorio=$2
    #local nome=$3
    #local num_paquete=$4

    if [[ $VERBOSE -eq 1 ]]; then
        # o do temp_space é preciso porque senón o nome sae cortado polo espazo
        nome=$(echo $nome | cut -d$SEP_CATEX -f2 | sed 's/$TEMP_SPACE/\ /g')
        desc=$(cat $FICH2 | grep $id_nome$SEP$LINGUA$SEP | cut -d$SEP_CATEX -f2)

        # mostrar ó usuario que se esta a instalar e o avance
        [[ $cont -ne 1 ]] && echo
        echo "$cont/$NUM_PROGS"
        echo "$nome"
        echo "$desc"
    fi

    pkg_install
}

$(pwd)/src/uteis/echo-texto -l $LINGUA -i "titulo.instalar_progs"

#pkgs=""
cont=1
while read line; do
    if [[ $line != \#* && -n $line ]]; then
        id_nome=$(echo $line | cut -d$SEP -f1)
        # o do temp_space é preciso porque senón o nome sae cortado polo espazo
        nome=$(echo $line | cut -d$SEP -f2 | sed 's/\ /$TEMP_SPACE/g')
        lst_distros=($(echo $line | cut -d$SEP -f3 | tr $SEP2 "\n"))
        #lst_repos=($(echo $line | cut -d$SEP -f4 | tr $SEP2 "\n"))
        repositorio=$(echo $line | cut -d$SEP -f4 | tr '[:upper:]' '[:lower:]')

        if [[ -n $lst_distros ]]; then
            for distro in "${lst_distros[@]}"; do
                if [[ $distro = $DISTRO ]]; then
                    #install_pkg $id_nome $repositorio $nome $cont
                    install_pkg
                    let cont++
                    #pkgs=$pkgs" "$id_nome
                    break
                fi
            done
        else
            #install_pkg $id_nome $repositorio $nome $cont
            install_pkg
            let cont++
            #pkgs=$pkgs" "$id_nome
        fi
    fi
done < $FICH

#install_pkg "$pkgs"

$(pwd)/src/uteis/echo-texto -l $LINGUA -i "final.ok"
