#! /bin/sh
#+ Autor:	Ran#
#+ Creado:	07/03/2020 22:33:09
#+ Editado:	2022/09/08 19:05:59.119423

#* Script que me permite meter os meus ficheiros de configuración en calquera máquina na que esté a trabalhar

# mirar se o script se executa como root
# de non, facer que así sexa
if [[ $(/usr/bin/id -u) != 0 ]]; then
    if whereis sudo &>/dev/null; then
        # correr o script de novo como sudo e cos parametros dados
        sudo $0 $*
        # para que non se execute dúas veces
        exit 0
    else
        # saída con erro
        exit 1
    fi
fi

FICH=$(pwd)"/media/arquivos.csv"

LINGUA=$(grep -w "lang" $(pwd)/.cnf | cut -d= -f2)
VERBOSE=$(grep -w "verbose" $(pwd)/.cnf | cut -d= -f2)
# ellminar proba
FOGAR=$(eval echo "~$(who -m | awk '{ print $1 }')")/proba
ACCEPT_ENCRIPT=$(grep -w "accept_encryption" $(pwd)/.cnf | cut -d= -f2)
CONTRASINAL=$(grep -w "passwd" $(pwd)/.cnf | cut -d= -f2)
CNFOLDER=$(grep -w "cnfolder" $(pwd)/.cnf | cut -d= -f2)
CNFOLDER_HOME=$(grep -w "cnfolder_home" $(pwd)/.cnf | cut -d= -f2)
CNFOLDER_ROOT=$(grep -w "cnfolder_root" $(pwd)/.cnf | cut -d= -f2)

case $LINGUA in
    gz)
        echo "► Pegando os ficheiros de configuración"
        ;;
    en)
        echo "► Pasting the configuration files"
        ;;
    cas)
        echo "► Pegando los ficheros de configuación"
        ;;
esac

[ $VERBOSE ] && cp -vupfr $(pwd)/$CNFOLDER/$CNFOLDER_HOME/. $FOGAR || cp -upfr $(pwd)/$CNFOLDER/$CNFOLDER_HOME/. $FOGAR
[ $VERBOSE ] && cp -vupfr $(pwd)/$CNFOLDER/$CNFOLDER_ROOT/. / || cp -upfr $(pwd)/$CNFOLDER/$CNFOLDER_ROOT/. /root

user=$(who -m | cut -d\  -f1)

while read line; do
    # ignorar todas as linhas que non comecen por 1
    if [[ $line = \1* ]]; then
        line=$(echo $line | cut -d, -f2)
        if [[ $line = \~* ]]; then
            line=$FOGAR$(echo $line | cut -d~ -f2)
        fi
        7z x $(echo $line | sed 's:/*$::').7z -o$(dirname $(echo $line | sed 's:/*$::')) -aoa -p$CONTRASINAL
        chown -R $user:$user $(echo $line | sed 's:/*$::')
        rm $(echo $line | sed 's:/*$::').7z
    fi
done < $FICH

case $LINGUA in
    gz)
        echo "◄ BO"
        ;;
    en)
        echo "◄ OK"
        ;;
    cas)
        echo "◄ OK"
        ;;
esac
